### PR TITLE
Update target for Launch Darkly 7.5.0 SDK

### PR DESCRIPTION
**Pull request by djprice-sms**
Modified the dependencies to reflect the URL for LD SDK 7.5.0

Updated the REAME file

created a box.json file

### CODE REVIEW

**Comment by SMSMichael** [comment]
@bdw429s this PR resolves #8.  LaunchDarkly is ending support for v6 of the Java SDK and we'd like to get our applications updated to v7 -  please let @djprice-sms or I know if you have any questions about these changes.

Thanks!

**Comment by bdw429s** [comment]
@SMSMichael @djprice-sms Thanks for the pull!  I assume the new SDK version is backwards compatible and no other CF changes are necessary in the CF portions?

**Comment by djprice-sms** [comment]
@bdw429s I have been using the new SDK locally and have not seen any issues. It is currently running in our QA environment as well.
cc: @SMSMichael

**Comment by bdw429s** [comment]
Thanks for the info!  Even  though this doesn't seem to be a breaking change, I've pushed it with a major version bump just in case. This is now published under version 3.0.0.

**Pull request merged**
